### ISSUE TITLE
Listagem de contribuidores via github api

### ISSUE THREAD

**Issue by Mazuh** [discentes-imd/IntegraTI-Web#28]
@sarahraquel, você queria implementar a listagem de contribuidores de alguma forma? Se quiser automatizar, é só fazer uma requisição get pra https://api.github.com/orgs/discentes-imd/members e tratar o json recebido. A REST API do Github permite fazer isso sem autenticações nem nada. :p

**Comment by sarahraquel** [comment]
Uhum, já tá feito, vou só fazer uns ajustes ao mostrar as infos

**Comment by Mazuh** [comment]
Aaaah, tá. Tinha procurado uma issue sobre isso e passei batido. Vou dar close nessa pra evitar repetição!
